import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/navbar";
import { Inter } from "next/font/google";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.className} h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <Navbar />
        {children}
        <footer className="text-center  bg-white/95 backdrop-blur border-t text-sm  border-slate-100 shadow-sm">
          Powered By GOUNI ICT Service
        </footer>
      </body>
    </html>
  );
}
